"""added more of the image information on the artwork class

Revision ID: b4643796fddd
Revises: c99152f4b18e
Create Date: 2024-10-22 00:00:20.889805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4643796fddd'
down_revision = 'c99152f4b18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('sold')
        batch_op.drop_column('likes')
        batch_op.drop_column('detail')
        batch_op.drop_column('price')
        batch_op.drop_column('year')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
